<a href="https://colab.research.google.com/github/krishisuthar4/Data-Cleaning-And-preprocessing/blob/main/cleaning_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd

In [15]:
df=pd.read_csv("/content/drive/MyDrive/titles.csv")

In [9]:
df.ndim

2

In [18]:
df.size

87750

In [11]:
df.shape

(5850, 15)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5850 entries, 0 to 5849
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    5850 non-null   object
 1   title                 5849 non-null   object
 2   type                  5850 non-null   object
 3   description           5832 non-null   object
 4   release_year          5850 non-null   int64
 5   age_certification     3231 non-null   object
 6   runtime               5850 non-null   int64
 7   genres                5850 non-null   object
 8   production_countries  5850 non-null   object
 9   seasons               2106 non-null   float64
 10  imdb_id               5447 non-null   object
 11  imdb_score            5368 non-null   float64
 12  imdb_votes            5352 non-null   float64
 13  tmdb_popularity       5759 non-null   float64
 14  tmdb_score            5539 non-null   float64
dtypes: float64(5), int64(2), object(8)
memory usage: 685.7+ KB

In [20]:
df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['fantasy', 'action', 'comedy']",['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
4,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,tt0061578,7.7,72662.0,20.398,7.600

Missing values before cleaning :

In [12]:
df.isnull()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,False,False,False,False,False,False,False,False,False,False,True,True,True,False,True
1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5845,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True
5846,False,False,False,False,False,True,False,False,False,True,False,False,False,True,True
5847,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False
5848,False,False,False,False,False,False,False,False,False,True,True,True,True,False,False
5849,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

id                         0
title                      1
type                       0
description               18
release_year               0
age_certification       2619
runtime                    0
genres                     0
production_countries       0
seasons                 3744
imdb_id                  403
imdb_score               482
imdb_votes               498
tmdb_popularity           91
tmdb_score               311
dtype: int64

Removinng duplicates

In [19]:
df.drop_duplicates(inplace=True)

Converting to lowercase

In [21]:
df['production_countries'] = df['production_countries'].str.lower()

In [24]:
df['genres'] = df['genres'].str.lower()

Removing brackets [] and single quotes ' using regex

In [26]:
df['genres'] = df['genres'].str.replace("[\[\]']", '', regex=True)

In [27]:
df['production_countries'] = df['production_countries'].str.replace("[\[\]']", '', regex=True)

Removing leading and trailing spaces

In [28]:
df['genres'] = df['genres'].str.strip()

In [29]:
df['production_countries'] = df['production_countries'].str.strip()

After these operations :

In [33]:
df.head(2)

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,documentation,us,1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"drama, crime",us,NaN,tt0075314,8.2,808582.0,40.965,8.179

Rename column headers (lowercase, replace spaces with underscores)

In [31]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [34]:
df.head(2)

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,documentation,us,1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"drama, crime",us,NaN,tt0075314,8.2,808582.0,40.965,8.179

Fixing data types

In [61]:
df['seasons'] = df['seasons'].astype('Int64')

Handling missing values

In [60]:
df['imdb_score'].fillna(df['imdb_score'].mean(), inplace=True)

In [38]:
df['title'].fillna("Unknown", inplace=True)

In [44]:
df['description'].fillna("Unknown", inplace=True)

In [56]:
df['age_certification'].fillna(df['age_certification'].mode()[0], inplace=True)

In [58]:
df['seasons'].fillna(df['seasons'].mode()[0], inplace=True)

<ipython-input-58-5778eae63dd5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['seasons'].fillna(df['seasons'].mode()[0], inplace=True)

In [62]:
num_cols = ['imdb_votes', 'tmdb_popularity', 'tmdb_score']
for col in num_cols:
    df[col].fillna(df[col].mean(), inplace=True)

<ipython-input-62-28b46205f59d>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [63]:
df['imdb_id'].fillna(df['imdb_id'].mode()[0], inplace=True)

<ipython-input-63-e79e403f3d2c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdb_id'].fillna(df['imdb_id'].mode()[0], inplace=True)

After filling missing values

In [64]:
df.isnull().sum()

id                      0
title                   0
type                    0
description             0
release_year            0
age_certification       0
runtime                 0
genres                  0
production_countries    0
seasons                 0
imdb_id                 0
imdb_score              0
imdb_votes              0
tmdb_popularity         0
tmdb_score              0
dtype: int64

In [65]:
df.to_csv("titles_cleaned.csv", index=False)
print("Cleaned file saved as: titles_cleaned.csv")

Cleaned file saved as: titles_cleaned.csv